semilla_primigenia: 100379.0
experimento: 9201.0
dataset: analistajr_competencia_2025.csv.gz
kaggle:
  competencia: data-mining-analista-jr-2025-b
  cortes:
  - 1800.0
  - 1900.0
  - 2000.0
  - 2100.0
  - 2200.0
  - 2300.0
  - 2400.0
